version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      types:
        patterns:
          - '@types/*'
      eslint:
        patterns:
          - 'eslint*'
          - '@eslint/*'
          - 'typescript-eslint'
      mocha:
        patterns:
          - 'mocha'
          - '@types/mocha'
          - 'chai'
          - '@types/chai'
          - 'sinon'
          - '@types/sinon'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
