-- 1.6.1: composite partial indexes for /v1/burns and owner-filtered queries
--
-- Two indexes, both following the same pattern: composite partial index
-- leading with `contract` (high-selectivity filter) + the secondary
-- column the query GROUPs / filters on, partial on the relevant
-- NOT NULL predicate. Same root cause for both: existing indexes either
-- omit `contract` (single-column on the secondary) or put the secondary
-- column LAST in a deeper composite (`atomicassets_assets_coll_schema_owner`)
-- so they can't pre-filter by (contract, secondary) efficiently.
--
-- ====================================================================
-- Index 1 — /v1/burns query
-- ====================================================================
--
-- The /v1/burns handler (src/api/namespaces/atomicassets/handlers/burns.ts)
-- runs roughly:
--
--   SELECT burned_by_account account, COUNT(*) AS assets
--   FROM atomicassets_assets asset
--   [LEFT JOIN atomicassets_templates template ON ...]   -- conditional, see 1.6.1 handler change
--   WHERE asset.contract = $1 AND asset.burned_by_account IS NOT NULL
--   GROUP BY asset.burned_by_account
--   ORDER BY assets DESC, account ASC
--   LIMIT $2 OFFSET $3
--
-- Without this index, the only usable index for the filter is
-- atomicassets_assets_burned_by_account (btree on burned_by_account alone),
-- which doesn't pre-filter by contract. The planner correctly rejects that
-- in favor of a Parallel Seq Scan on the 80+ GB atomicassets_assets table.
-- On the FACINGS WAX-mainnet replica (1.5.0 schema, ~86 GB table, ~61.6M
-- rows past the WHERE filter), this scan averages 143 seconds per
-- /v1/burns call. Compounded across the API's autoscaler fleet it took out
-- atomichub-blockchain-api with 30s app-side timeouts and cascaded into a
-- 6-hour crashloop on 2026-05-18.
--
-- After this index + the handler-side conditional-JOIN change (see
-- burns.ts in this PR), measured EXPLAIN ANALYZE drops to ~27 sec on the
-- same data (5.3× faster). Index size on WAX-mainnet: 1.7 GB partial.
CREATE INDEX IF NOT EXISTS atomicassets_assets_contract_burned_partial
    ON atomicassets_assets (contract, burned_by_account)
    WHERE burned_by_account IS NOT NULL;

-- ====================================================================
-- Index 2 — /atomicassets owner-filtered queries (profile inventory)
-- ====================================================================
--
-- The most-hammered family of queries in pg_stat_statements on FACINGS
-- WAX-mainnet (sum of `total_exec_time` > 169 hours, ~160k calls):
--
--   SELECT asset.asset_id
--   FROM atomicassets_assets asset
--   WHERE asset.contract = $1 AND "asset".owner = $2 [AND "asset".collection_name = $3]
--   ORDER BY asset.asset_id DESC
--   LIMIT $4 OFFSET $5
--
-- Plus the variants:
--   SELECT collection_name, schema_name, template_id, COUNT(*)
--   FROM atomicassets_assets
--   WHERE contract = $1 AND owner = $2
--   GROUP BY contract, collection_name, schema_name, template_id;
--
--   SELECT COUNT(*) FROM (SELECT asset_id FROM atomicassets_assets WHERE contract = $1 AND owner = $2 ...);
--
-- All of these power the user profile / inventory pages.
--
-- The existing index `atomicassets_assets_owner_btree` (single column,
-- non-partial) is what the planner currently uses. It works correctly
-- for small users (e.g., 2,962 assets → cost 3316, fast) but degrades
-- catastrophically for users with large inventories because the planner
-- has to fetch the heap to filter by `contract` (and sometimes
-- `collection_name`). On 2026-05-18 we observed 54 concurrent owner-filter
-- queries on the replica with avg duration 129 seconds, max 253 seconds.
--
-- A composite partial index leading with `contract` then `owner` lets
-- the planner satisfy both the high-cardinality contract filter and the
-- secondary owner filter via a single index seek, with no heap fetch
-- needed unless the application also filters by columns this index
-- doesn't cover (collection_name, template_id, etc).
CREATE INDEX IF NOT EXISTS atomicassets_assets_contract_owner_partial
    ON atomicassets_assets (contract, owner)
    WHERE owner IS NOT NULL;

-- ====================================================================
-- Index 3 — atomicmarket /v1/sales template_mint-sorted queries
-- ====================================================================
--
-- Lives in the atomicassets-api repo because this repo's migration
-- pipeline (src/filler/upgrade-db.ts) is the single entry point for
-- DDL on the shared atomic* schema; atomicmarket-api uses the same
-- pipeline and runs after atomicassets is up.
--
-- The marketplace listing query at e.g.
--   https://wax.atomichub.io/market?blockchain=wax-mainnet&order=asc&sort=template_mint&symbol=WAX
-- (handler: src/api/namespaces/atomicmarket/handlers/sales.ts via
-- the LISTED filter table partition) runs roughly:
--
--   SELECT listing.sale_id
--   FROM atomicmarket_sales_filters_listed listing
--   WHERE listing.market_contract = $1
--     AND listing.settlement_symbol = $2
--     -- (sale_state = 1 is implicit in the LISTED partition)
--   ORDER BY lower(listing.template_mint) ASC NULLS LAST, listing.sale_id
--   LIMIT 1000
--
-- The existing `atomicmarket_sales_filters_listed_lower_idx` is a
-- single-column expression index on `lower(template_mint)` (49 MB on
-- the FACINGS WAX-mainnet partition, ~1.73M rows). It works when no
-- column filters are added (planner picks Index Scan + Incremental
-- Sort, cost ~236 for LIMIT 1000) but cannot pre-filter by
-- (market_contract, settlement_symbol). When the query adds those
-- filters — which the marketplace UI always does — using the index
-- requires a heap fetch per entry to evaluate the filter, and the
-- planner switches to Parallel Seq Scan + full Sort over the
-- partition (cost 314,329 on WAX-mainnet, ~30 sec wall time).
--
-- The app-side timeout for atomichub-blockchain-api is 20 sec, so
-- the user-facing symptom is HTTP 408 with body
-- `{"success":false,"message":"Max database query time exceeded.
-- Please try to add more filters to your query."}`.
--
-- A partial composite leading with the filter columns then the sort
-- expression lets the planner satisfy both the WHERE prefix and the
-- ORDER BY via a single index range scan, with the sale_id tiebreaker
-- included to keep the sort 1:1 with the existing `lower_idx`
-- behavior.
--
-- This index is a superset of `atomicmarket_sales_filters_listed_lower_idx`
-- for any query that also filters on (market_contract, settlement_symbol),
-- which is the only shape the marketplace UI uses. Operators may drop
-- the old single-column lower_idx after deploying this one, but the
-- migration leaves it in place because some external integrations may
-- still query the partition without those filters.
CREATE INDEX IF NOT EXISTS atomicmarket_sales_filters_listed_mkt_settle_mint_partial
    ON atomicmarket_sales_filters_listed (market_contract, settlement_symbol, lower(template_mint), sale_id)
    WHERE lower(template_mint) IS NOT NULL;

-- ====================================================================
-- Index 4 — covering partial for /v1/accounts/:account (profile dropdown)
-- ====================================================================
--
-- The /v1/accounts/:account handler (handlers/accounts/getAccountAction.ts)
-- runs the asset-count-by-template query exactly once per page load:
--
--   SELECT collection_name, schema_name, template_id, COUNT(*) as assets
--   FROM atomicassets_assets asset
--   WHERE contract = $1 AND owner = $2
--   GROUP BY contract, collection_name, schema_name, template_id
--   ORDER BY assets DESC
--
-- Index 2 above (atomicassets_assets_contract_owner_partial) gets the
-- planner to use an Index Scan for the WHERE, but the GROUP BY columns
-- (collection_name, schema_name, template_id) are NOT in that index's
-- key — so each matched index entry forces a random heap fetch to read
-- them. On warm cache that's fast (~14 ms for 10k NFTs / 161 collections
-- on WAX-mainnet). On cold cache the 60+ MB of heap pages hit disk and
-- the query crosses 19 sec → 408 to the client → empty "All collections"
-- dropdown on the profile page (and empty "Estimated Value" if the same
-- handler call also feeds inventory pricing). Reproduced 2026-05-18 on
-- account `intqi.wam` (10,642 NFTs / 161 collections).
--
-- Adding the GROUP BY columns via INCLUDE makes the query an
-- Index-Only Scan when the visibility map is fresh, eliminating heap
-- fetches entirely. The b-tree key stays (contract, owner) so range
-- scans by owner are unaffected; the leaf pages just carry three extra
-- columns each. Cost on WAX-mainnet: roughly 3-4× the existing partial
-- (2.2 GB → ~7-8 GB), which is worth it because this query is one of
-- the hottest profile-page paths and the value of consistent cold-cache
-- latency outweighs the storage.
--
-- This index is a strict superset of Index 2 for this query shape only;
-- it does NOT supersede Index 2 for the bare `WHERE contract = $1 AND
-- owner = $2` shape (e.g., the inventory list query in
-- src/api/namespaces/atomicassets/handlers/assets.ts), where the smaller
-- key-only partial is cheaper to walk.
CREATE INDEX IF NOT EXISTS atomicassets_assets_contract_owner_cover_partial
    ON atomicassets_assets (contract, owner)
    INCLUDE (collection_name, schema_name, template_id)
    WHERE owner IS NOT NULL;

-- ====================================================================
-- IMPORTANT — existing-cluster operator note (applies to all indexes)
-- ====================================================================
--
--   This migration runs inside a BEGIN/COMMIT transaction (see
--   src/filler/upgrade-db.ts), so CREATE INDEX CONCURRENTLY here would
--   abort with `CREATE INDEX CONCURRENTLY cannot run inside a transaction
--   block`. The CREATE INDEX statements above are BLOCKING — on existing
--   populated clusters (atomicassets_assets at 80+ GB, the listed sales
--   partition at 2+ GB), each will hold an ACCESS EXCLUSIVE lock on its
--   table for ~30 sec to 30 min during the build, stalling the filler.
--
--   For existing clusters, operators MUST pre-create all four indexes
--   non-blockingly BEFORE bumping to 1.6.1:
--
--     psql -d eca_wax_mainnet \
--       -c "SET statement_timeout = 0" \
--       -c "CREATE INDEX CONCURRENTLY IF NOT EXISTS
--             atomicassets_assets_contract_burned_partial
--           ON atomicassets_assets (contract, burned_by_account)
--           WHERE burned_by_account IS NOT NULL"
--
--     psql -d eca_wax_mainnet \
--       -c "SET statement_timeout = 0" \
--       -c "CREATE INDEX CONCURRENTLY IF NOT EXISTS
--             atomicassets_assets_contract_owner_partial
--           ON atomicassets_assets (contract, owner)
--           WHERE owner IS NOT NULL"
--
--     psql -d eca_wax_mainnet \
--       -c "SET statement_timeout = 0" \
--       -c "CREATE INDEX CONCURRENTLY IF NOT EXISTS
--             atomicmarket_sales_filters_listed_mkt_settle_mint_partial
--           ON atomicmarket_sales_filters_listed
--               (market_contract, settlement_symbol, lower(template_mint), sale_id)
--           WHERE lower(template_mint) IS NOT NULL"
--
--     psql -d eca_wax_mainnet \
--       -c "SET statement_timeout = 0" \
--       -c "CREATE INDEX CONCURRENTLY IF NOT EXISTS
--             atomicassets_assets_contract_owner_cover_partial
--           ON atomicassets_assets (contract, owner)
--           INCLUDE (collection_name, schema_name, template_id)
--           WHERE owner IS NOT NULL"
--
--   The IF NOT EXISTS clauses above then make this migration a no-op
--   for pre-created clusters.
--
--   For NEW deployments: both tables are empty during first-boot init
--   (handler.setup() creates them before this migration runs), so the
--   CREATE INDEX statements are effectively instant. No operator action
--   needed.
