-- 1.6.2: hotfix release for the 2026-05-18 1.6.1 rollout. Ships:
--
--  1. src/filler/upgrade-db.ts strips `-- ...` line comments before
--     splitting on `;` so prose semicolons in deferred SQL comments
--     cannot fragment statements (1.6.1 crash-loop root cause).
--  2. definitions/migrations/1.6.1/{atomicassets,atomicmarket}-deferred.sql
--     have all prose `;` rewritten to periods/commas (defense in depth
--     in case the parser fix is ever reverted).
--  3. definitions/migrations/1.6.1/database.sql now UPDATEs dbinfo.version
--     -- previously a no-op that left chains re-running 1.6.1 every boot.
--
-- The UPDATE below advances dbinfo to 1.6.2 so subsequent boots skip the
-- migration loop entirely (currentVersion >= all availableVersions).
UPDATE dbinfo SET "value" = '1.6.2' WHERE name = 'version';
